Document: pebble-sdk
Title: Debian pebble-sdk Manual
Author: <insert document author here>
Abstract: This manual describes what pebble-sdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pebble-sdk/pebble-sdk.sgml.gz

Format: postscript
Files: /usr/share/doc/pebble-sdk/pebble-sdk.ps.gz

Format: text
Files: /usr/share/doc/pebble-sdk/pebble-sdk.text.gz

Format: HTML
Index: /usr/share/doc/pebble-sdk/html/index.html
Files: /usr/share/doc/pebble-sdk/html/*.html
